<?php

namespace IdeaMaker\Facades;

use Nette\Application\AbortException;
use Nette\ArrayHash;
use Nette\Database\Connection;
use Nette\Diagnostics\Debugger;
use Nette\Http\FileUpload;
use Nette\Security\User;

class ActualityFacade extends Facade
{
    protected $languages;
    public function __construct($languages, Connection $db, User $user)
    {
        parent::__construct($db, $user); // TODO: Change the autogenerated stub
        $this->languages = $languages;
    }

    protected function beforeSave(ArrayHash &$data)
    {

        parent::beforeSave($data);
    }


    public function getLangTable() {
        return $this->connection->table('actuality_lang');
    }

    public function save(ArrayHash $data)
    {


        $this->connection->beginTransaction();
        try {
            $data['id'] = $data['id'] ?:NULL;
            $localizedData = (array) $data;
            if (isset($data['id'])) {
                $defaultData['id'] = $data['id'];
            }
            $defaultData['is_active'] = $data['is_active'];

            unset($localizedData['parent_id']); // unset default data

            foreach ($this->languages as $language) {
                $localizedData[$language]['actuality_id'] = $localizedData['id'];
                $localizedData[$language]['lang'] = $language;
                foreach(array('perex', 'title', 'slug', 'content') as $column) {
                    $localizedData[$language][$column] = $localizedData[$column.'_'.$language];
                }
            }

            $this->prepareCreatedAt($defaultData);
            $this->prepareUpdatedAt($defaultData);
            $this->prepareCreatedBy($defaultData);
            $this->prepareUpdatedBy($defaultData);

            $defaultData['image'] = $this->saveImage($data['image']);

            if (isset($data['id'])) { // update
                $this->connection->table('actuality')->where(array('id'=>$data['id']))->update($defaultData);
                foreach($this->languages as $language) {
                    $this->prepareUpdatedAt($localizedData[$language]);
                    
                    $result = $this->connection->table('actuality_lang')->where(array('actuality_id'=>$data['id'], 'lang'=>$language))->update($localizedData[$language]);
//                    Debugger::barDump($defaultData, 'default data');
//                    Debugger::barDump($localizedData, 'lcalized data');
//                    exit;
                }
            } else { // insert

                $localizedData['id'] = $data['id'] = $this->connection->table('actuality')->insert($defaultData)->id;
                $this->prepareUpdatedAt($localizedData[$language]);
                $this->prepareCreatedAt($localizedData[$language]);
                if ($localizedData['id']) {
                    foreach ($this->languages as $language) {
                        $localizedData[$language]['actuality_id'] = $localizedData['id'];
                        $this->connection->table('actuality_lang')->insert($localizedData[$language]);
                    }
                } else {
                    throw new AbortException;
                }
            }
            $this->connection->commit();
        }catch (\Exception $e) {
            $this->connection->rollBack();
            Debugger::barDump($e);
//            exit;
            throw $e;
        }


        return $data['id'];
    }

    public function delete($id)
    {
        return $this->getTable()->find($id)->delete();
    }


    protected function saveImage(FileUpload $image)
    {
        if ($image->isOk()) {
            $image->move(dirname(dirname(__DIR__)).'/web/actuality/'.$image->sanitizedName);
            return '/actuality/'.$image->sanitizedName;
        }
        return '';
    }




}