<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Kdyby\\BootstrapFormRenderer\\' => $vendorDir . '/kdyby/bootstrap-form-renderer/src',
    'Grido' => $vendorDir . '/o5/grido',
);
